baseurl = "https://example.org"
languageCode = "en-us"
title = "Lithium Theme"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = ""
[[menu.main]]
    name = "Twitter"
    url = ""

[params]
    description = ""
    
    # Specify custom CSS (paths are relative to /static
    #custom_css = ["css/foo.css", "css/bar.css"]

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

